-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."user"
(
    id serial NOT NULL,
    nome character varying COLLATE pg_catalog."default" NOT NULL,
    email character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tarefa
(
    id serial NOT NULL,
    nome character varying COLLATE pg_catalog."default" NOT NULL,
    descricao character varying COLLATE pg_catalog."default" NOT NULL,
    data timestamp without time zone NOT NULL DEFAULT now(),
    prioridade integer NOT NULL,
    status character varying COLLATE pg_catalog."default" NOT NULL,
    "userId" integer,
    CONSTRAINT "PK_df7268dfad5b4b665bcee2ae8b5" PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.tarefa
    ADD CONSTRAINT "FK_1f1ef3fd3d2d15728d43a5b5ba7" FOREIGN KEY ("userId")
    REFERENCES public."user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;